import mongoose from 'mongoose';
import {
    USER_STATUS,
    UserStatus,
    BANNER_DEFAULT_COLOR,
} from '../../domain/user.constant.js';
import {
    USERNAME_MIN_LENGTH,
    USERNAME_MAX_LENGTH,
    BIO_MAX_LENGTH,
} from '../../../../shared/constants/index.js';

/**
 * User profile schema — stored in the `users` collection.
 *
 * Owned by the user bounded context as a profile projection.  Credential
 * fields (password, isVerified, email) are absent; they live in the `credentials`
 * collection managed by the auth module.
 *
 * The `_id` here is auto-generated by MongoDB, giving the User entity its own
 * independent identity. The `authId` field maintains a reference to the `AuthUser`
 * credential record created by the auth module.
 */
const userSchema = new mongoose.Schema(
    {
        authId: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },
        username: {
            type: String,
            required: true,
            unique: true,
            minLength: USERNAME_MIN_LENGTH,
            maxLength: USERNAME_MAX_LENGTH,
        },
        displayName: {
            type: String,
            default: null,
        },
        avatar: {
            type: String,
            default: null,
        },
        bio: {
            type: String,
            maxLength: BIO_MAX_LENGTH,
            default: null,
        },
        banner: {
            type: String,
            default: null,
        },
        bannerColor: {
            type: String,
            default: BANNER_DEFAULT_COLOR,
        },
        dateOfBirth: {
            type: Date,
            required: true,
        },
        status: {
            type: String,
            enum: USER_STATUS,
            default: UserStatus.OFFLINE,
        },
        lastOnline: {
            type: Date,
            default: null,
        },
    },
    { timestamps: true }
);

userSchema.index({ status: 1, lastOnline: -1 });

const transform = (doc, ret) => {
    delete ret.__v;
    return ret;
};

userSchema.set('toJSON', { transform });
userSchema.set('toObject', { transform });

export const UserModel = mongoose.model('User', userSchema, 'users');
