import mongoose from 'mongoose';
import {
    USER_STATUS,
    UserStatus,
    BANNER_DEFAULT_COLOR,
} from '../../domain/user.constant.js';

/**
 * User profile schema — stored in the `users` collection.
 *
 * Owned entirely by the user bounded context.  Credential fields (password,
 * isVerified) are absent; they live in the `credentials` collection managed
 * by the auth module.
 *
 * The `_id` here is auto-generated by MongoDB, giving the User entity its own
 * independent identity. The `authId` field maintains a reference to the `AuthUser`
 * credential record created by the auth module.
 */
const userSchema = new mongoose.Schema(
    {
        authId: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            unique: true,
        },
        email: {
            type: String,
            required: true,
            unique: true,
        },
        username: {
            type: String,
            required: true,
            unique: true,
            minLength: 3,
            maxLength: 30,
        },
        displayName: {
            type: String,
            default: null,
        },
        avatar: {
            type: String,
            default: null,
        },
        bio: {
            type: String,
            maxLength: 190,
            default: null,
        },
        banner: {
            type: String,
            default: null,
        },
        bannerColor: {
            type: String,
            default: BANNER_DEFAULT_COLOR,
        },
        dateOfBirth: {
            type: Date,
            required: true,
        },
        status: {
            type: String,
            enum: USER_STATUS,
            default: UserStatus.OFFLINE,
        },
        lastOnline: {
            type: Date,
            default: null,
        },
    },
    { timestamps: true }
);

userSchema.index({ status: 1, lastOnline: -1 }, { sparse: true });

const transform = (doc, ret) => {
    delete ret.__v;
    return ret;
};

userSchema.set('toJSON', { transform });
userSchema.set('toObject', { transform });

export const UserModel = mongoose.model('User', userSchema, 'users');
