const UI_TEXT = {
  login: {
    header: 'Welcome back!',
    subtitle: "We're so excited to see you again!",
    forgotPassword: 'Forgot your password?',
    loginLink: 'Login',
    needAccount: 'Need an account?',
    registerLink: 'Register',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailRequiredWarn: 'Email is required',
    invalidEmailWarn: 'Please enter a valid Email',
    passwordRequiredWarn: 'Password is required',
    passwordValidationWarn: 'Password must be at least 6 characters long',
  },
  register: {
    header: 'Create an account',
    emailLabel: 'Email',
    displayNameLabel: 'Display Name',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    dateOfBirthLabel: 'Date of Birth',
    emailRequiredWarn: 'Email is required',
    invalidEmailWarn: 'Please enter a valid email',
    displayNameRequiredWarn: 'Display Name is required',
    usernameRequiredWarn: 'Username is required',
    usernameValidationWarn: 'Username must be at least 3 characters long',
    usernameMaxValidationWarn: 'Username should be maximum of 30 characters',
    passwordRequiredWarn: 'Password is required',
    passwordValidationWarn: 'Password must be at least 6 characters',
    dateOfBirthRequiredWarn: 'Date of Birth is required',
    invalidDateOfBirthWarn: 'Please enter a valid date',
    agreeToTermsWarn: 'You must agree to the terms',
    agreeToTermsPrefix: "I agree to Sync Space's",
    termsLink: 'Terms',
    submit: 'Create Account',
    submitting: 'Creating Account...',
    hasAccount: 'Already have an account?',
    loginLink: 'Login',
  },
};

export default UI_TEXT;
